name: simple_responsive
description: simple_responsive provides a simple method for creating responsive user interfaces.
version: 0.0.1
repository: https://github.com/fronio/simple_responsive

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
